{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "rochallor.fullname" .) }}
  labels:
    {{- include "rochallor.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.postgresql.dsn | quote }}
{{- end }}
{{- if and
      (eq .Values.engine.dispatchMode "kafka_outbox")
      (eq .Values.kafka.transport "sasl_scram_tls")
      (not .Values.kafka.existingSecret)
}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-kafka" (include "rochallor.fullname" .) }}
  labels:
    {{- include "rochallor.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.kafka.saslUsername | quote }}
  password: {{ .Values.kafka.saslPassword | quote }}
{{- end }}
